### ISSUE TITLE
As an anonymous user — I want to visit a wordpress test site hosted in the cloud — so that I can see some blog posts and other content types there

### ISSUE THREAD

**Issue by sumeetpareek** [sumeetpareek/wordpress-one-and-half-days#1]
## TASK ⚠️  from end user perspective ⚠️ 

As an anonymous user — I want to visit a wordpress test site hosted in the cloud — so that I can see some blog posts and other content types there

## DONE WHEN

- [x] hosted site is created, with basic site admin options configured
- [x] site is launched, and accessible to anonymous user on url .. we got this one .. https://tigertest726600843.wordpress.com/
- [ ] create some local development tasks

## CHECKLIST

- [x] start a test site 
- [x] follow through dashboard steps
- [x] tinker with homepage blocks, content, grid, placement, settings, etcetera
- [x] tinker with site menu stuff 
- [x] launch without custom domain

**Comment by sumeetpareek** [comment]
1. quick sign up on wordpress.com using google
2. created test site
3. very helpful dashboard and links to get started

![image](https://user-images.githubusercontent.com/140441/116895311-10b25700-ac01-11eb-99ba-1939a3e84265.png)

**Comment by sumeetpareek** [comment]
updated general site settings
edit homepage had a tour widget
the undo functionality is super cool, rest of it too
![image](https://user-images.githubusercontent.com/140441/116896234-0775ba00-ac02-11eb-816c-79d4deeabcf5.png)

there was a top list view showing the full tree of blocks
added tiger photo as the cover
explored options to change properties, block position, etcetera
added a youtube embed block, moved it around
added a quote block
changed a layout grid under a group from 2-columns to 3-columns
added an image block with joe exotic photo from url
saved updates and previewed changes for desktop, mobile, etc

## learn later

- [ ] what are reusable blocks, how do they work, what usecases are the best for?
- [x] block groups, how do they work, what usecases are the best for?
- [ ] stuff from the learn documentation section https://wordpress.com/learn/quick-start-guide/

## trouble

youtube embed block .. by itself .. or as a group .. remained nested .. the same block did not move to top level block/group .. could delete and add a new one .. but need to see how to get it to move to the right place in the layout tree

![image](https://user-images.githubusercontent.com/140441/116900931-51ad6a00-ac07-11eb-8631-3471a7fc2bb6.png)

**Comment by sumeetpareek** [comment]
some plugins can be started or unstared .. like jetpack and global styles .. they stay near top right of the menu .. 
blank canvas theme for single page websites
text to audio for anchor podcasts .. cool new things 

![image](https://user-images.githubusercontent.com/140441/116902031-a998a080-ac08-11eb-9c06-6fab27ca8054.png)


## try later 

maybe as a development task add another item to the "what's new" block content

**Comment by sumeetpareek** [comment]
- [x] Create a Menu
- [x] Add Menu Items
- [x] Menu Display Location
- [x] Automatically Add Pages to your Menu
- [x] Reorder Menu Items
- [x] Create Drop-Down Menus
- [x] Make an Unclickable Menu Item
- [x] Delete Menu Items
- [x] Customize the Menu Item Text
- [ ] Customize the Menu Design
- [x] Save your Changes
- [x] Frequently Asked Questions
- [ ] Menus in WP Admin
- [ ] Advanced Menu Settings

admin > appearance > menus > create new menu (primary and TODO were already there)
can link any existing stuff (pages, tags, etc) or create custom links

## learn later

- [ ] how do you add a new menu location? maybe just place with layout > columns > block

## try later

maybe as development task create random pages link that only operates with a limited subset of featured items, or prevents some items .. learn from the `twenty thirteen theme`

![image](https://user-images.githubusercontent.com/140441/116917201-56c8e400-ac1c-11eb-959e-4f842c6b5602.png)
