### ISSUE TITLE
As seasoned drupal developer resurrecting wordpress — I want to run and debug wordpress via a local development environment — so I can have the setup used by wordpress core and plugin developers

### ISSUE THREAD

**Issue by sumeetpareek** [sumeetpareek/wordpress-one-and-half-days#2]
## TASK ⚠️  from end user perspective ⚠️ 

As seasoned drupal developer resurrecting wordpress — I want to run and debug wordpress via a local development environment — so I can have the setup used by wordpress core and plugin developers

## DONE WHEN

- [x] get a local setup and site running
- [x] effect small change in a plugin
- [x] debug and step through a plugin
- [ ] create new issue to try gutenberg plugin development https://bebroide.medium.com/how-to-easily-develop-with-react-your-own-custom-fields-within-gutenberg-wordpress-editor-b868c1e193a9

## CHECKLIST

- [x] get latest vagrant and virtualbox .. try the VVV setup
- [x] expunge vagrant plugins and get vagrant-hostsupdater working
- [ ] explore the codebase in browser https://make.wordpress.org/core/handbook/contribute/codebase/
- [x] login the local admin panel and explore

**Comment by sumeetpareek** [comment]
there is community developer documentation on using various methods
going ahead with `vvv` vagrant setup
![image](https://user-images.githubusercontent.com/140441/116926804-d5c41980-ac28-11eb-9b0b-127ece38b361.png)

looks like I was on really old versions .. will quickly try to update
```
VirtualBox -h                                                                                                                                                                                                                              
Oracle VM VirtualBox Manager 5.1.28
# latest is 6.1.22

vagrant --version                                                                                                                                                                                                                          
Vagrant 2.0.0
# latest is 2.1.16
```

updated virtualbox and vagrant .. 

### ⚠️  error on installing vagrant-hostsupdater plugin

and installed hostupdated plugin
```
vagrant plugin install vagrant-hostsupdater                                                                                                                                                                                             

Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Fetching vagrant-auto_network-1.0.3.gem
Fetching vagrant-hostmanager-1.8.9.gem
Fetching vagrant-hostsupdater-1.2.4.gem
Fetching micromachine-3.0.0.gem
Fetching vagrant-vbguest-0.29.0.gem
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unable to resolve dependency: user requested 'vagrant-auto_network (= 1.0.2)'
```

trying to expunge all plugins ... it worked
```
vagrant plugin expunge --reinstall

https://github.com/hashicorp/vagrant/issues/8054

sudo vagrant plugin install vagrant-hostsupdater                                                                                                                                                                                          

Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (1.2.4)'!
```

following VVV instructions
https://varyingvagrantvagrants.org/docs/en-US/installation/
```
git clone -b stable https://github.com/Varying-Vagrant-Vagrants/VVV.git ~/vvv-local
cd ~/vvv-local
vagrant plugin install --local
```
trying to get everything and have it up 🤞 
```
vagrant up
```

got everything working ... now to step through the code and change something
![image](https://user-images.githubusercontent.com/140441/116932234-fba0ec80-ac2f-11eb-9d47-cd640c313a04.png)

**Comment by sumeetpareek** [comment]
found default credentials here
https://varyingvagrantvagrants.org/docs/en-US/default-credentials/
was able to login as admin in site one

**Comment by sumeetpareek** [comment]
activated the `hello dolly` plugin
appended a test string to the return value of `hello_dolly_get_lyric()` and it worked 👍 

installed and activated the WP maintenance mode plugin https://wordpress.org/plugins/wp-maintenance-mode/
tried various settings of it and it works

![image](https://user-images.githubusercontent.com/140441/116938585-fac08880-ac38-11eb-882d-fc0ef5a5751d.png)

**Comment by sumeetpareek** [comment]
trying to turn on debugger > setup break points > and step through execution
opened wordpress code base in phpstrom
```
cd github/vvv-local/www/wordpress-one/public_html
pstorm .
```
will follow this 
https://varyingvagrantvagrants.org/docs/en-US/references/xdebug-and-phpstorm/

confirmed in phpinfo that xdebug is not active yet
http://vvv.test/phpinfo/

enabled xdebug with php restart
`vagrant ssh -c "switch_php_debugmod xdebug"`

edited phpstorm settings
```
confirmed project root in directory settings
php language level set to 7.4
added include path to /Users/sumeetpareek/github/vvv-local/www/wordpress-one/public_html
Run > Edit configurations
added new PHP Remote Debug
filtered by IDE key set to VVVDEBUG
```
## 🚫  error .. phpstorm xdebug server setup

there is no server in the server drop down and apply button says server must be selected
manually setting server like this did not help
all attempts failed
https://blog.jetbrains.com/phpstorm/2016/06/debugging-vvv-vagrant-setup-with-phpstorm/
https://varyingvagrantvagrants.org/docs/en-US/references/xdebug-and-phpstorm/
https://cnpagency.com/blog/debugging-wordpress-on-vvv-with-phpstorm/

found out that vvv has a new xdebug info button
http://vvv.test/xdebuginfo/
seems like the setup has moved to xdebug `3.0.3`
which had another helpful blog
https://www.seanhayes.biz/vvv-and-xdebug-3-using-improved-xdebug-with-varying-vagrant-vagrants-and-phpstorm/

ran the debug validation script
confirmed problem reported in above blog .. fixing it with the recommended config changes in `VVVROOT/config/php-config/xdebug.ini`
![image](https://user-images.githubusercontent.com/140441/117051180-40865b00-ace4-11eb-90f4-2d195f5bee30.png)

changed phpstorm PHP xdebug port from 9000 to 9003
appended to xdebug config.ini
```
xdebug.client_host =192.168.50.1
xdebug.mode =debug
```

reloaded vagrant and provisioned again `vagrant reload --provision`

none of the wordpress site or vvv dashboard was accessible ... halted and up-ed vagrant again

the change in client host did not work
![image](https://user-images.githubusercontent.com/140441/117054462-1fc00480-ace8-11eb-9d23-16bf7a218251.png)

trying to undo it and just leave things where phpstorm port is set to 9003

even with all of this .. now the debugger connects .. but it never stops at any breakpoint .. even if `break at first line is enabled` 

![image](https://user-images.githubusercontent.com/140441/117062940-163b9a00-acf2-11eb-8d95-06ae071eced0.png)

**Comment by sumeetpareek** [comment]
## ✅ debugger finally worked, yaaas


after lots of trails and errors .. `xdebug + phpstorm + vvv` worked 
- default xdebug config shipped with vvv had to be changed ... NOT `xdebug.mode=debug,develop,profile` ... BUT just to `xdebug.mode=debug`
- the port had to be changed from 9000 to 9003 in ... phpstorm > preferences > PHP > Debug
- https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_mode

![image](https://user-images.githubusercontent.com/140441/117152664-3cac1480-ad88-11eb-9f81-8f924359fddc.png)

---

and we can inspect plugins, actions, hooks, and all of the stuff now 
![image](https://user-images.githubusercontent.com/140441/117152245-d921e700-ad87-11eb-9283-c67a75593fe9.png)
